apiVersion: ENC[AES256_GCM,data:UPQ=,iv:cd1sVWknmS3Eb60vbqAPkiTQ32ICxAW5dZPUdDMk4Tg=,tag:Fv3VmUCD/eZHclW5DDJI4w==,type:str]
kind: ENC[AES256_GCM,data:SeW+7Ufe,iv:yKl2vsYVVTnidpA70UicNSfOkLgSRQdp1wJAYw6uJ4Q=,tag:qUpMDRahpTdsQb53qyzFIw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rqLYKVy9JWGVaGTDCQbH/5zz7YNri3Y2DOjDHA==,iv:S0IItJIMuOFUMOX1F5cKRYhKAPelDkeQf7B1DgcJUlk=,tag:44VbcfW2SBlN2Xj7PCufag==,type:str]
    namespace: ENC[AES256_GCM,data:iXcbVQ7BQRqkjQ==,iv:Mwc0RJGc9LllIv2nnWdW/A/6cdp58Mu1ngdtlMA35oM=,tag:cUXryk6vtvhq/bj3hPClPg==,type:str]
type: ENC[AES256_GCM,data:lzKf1zwZ,iv:asQo8pzxLFCmTtWBpZ9DpDWGjiCK7ezq87+gvSn09tM=,tag:IMLJiY7+yGMXvGe7EuAuVA==,type:str]
stringData:
    webhook-url: ENC[AES256_GCM,data:6YQ6kVTh076V8EqPcCCX8/wL9D7NPdkai5tglH5oMeqCXrTBddbikXdHruP7YP5Oai82syl9Xznmzj40Knip/+YDz2XvsMBDLkiX176ITU6Im2z4A3z7BNuFFBipzrNsGPbRUdOjH1p+KNguzmK2XukZxrH04tNgPvpNXA==,iv:6NPPgCdIxHeYvVXtcXMOaSpdBU0XNXltzsULRON2r8Q=,tag:6HGk8HKbdw7RCAFlE4wtCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a0VPR0tRbkhJVGx1K29k
            MkovdVkxeWpGd0puMmltN3ZYbTlwd1FUWkhJCnl0SjBCbEhWWWNuNzRhdlVVSTY0
            MlU3ZVVwa1V6MXJjNHB2TllDdVFEblkKLS0tIGRQVnJmNFRucmZJK1NJTVp3U2Vq
            TlUvd015N2VzTzJobkRkeXdtYitWQnMKmhp9NOUkamf0rFEjMfgSMGpU1H4zrM4e
            D09JbGdV916xLNUR9dUNIjA8mqj/r4yRbr7m8+3VNc18ynftVMYwdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK2tJc3QzUDJ6Q2FLQmRP
            VDZQVk43QWdlOFFHYTBqdXdOOFVuSFBhd2owCjk4NEpKQjhHdGRQeGtobE5WTDEw
            Ym9uN0x4K1NoUWwwNFNkU21YdkdSaXMKLS0tIFRwbitJMUxTak5ndG15WTJ5bFdq
            QmZPUU85Nk9zdUgxVkFROVk2RlZ1em8KPj0N+h2K9/tdKUj/UM60t2Df+34CllK5
            e0NeEViTAt/w/6+hY8zfYbGRfSMtH/njbZTXnNcaVTfXgXXWWF9QgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q2x5TFpwUjRhRWIwQ3lr
            WlZVQU5tVVhFK3FaMFR2ZzZYUlRyRVhJTVY4Ck1qRVQ2S3FnYmhzWDMwbi8wTC9s
            NHRyNWJXRC9KMkdNT1pnbTJWb3JkeFEKLS0tIElEbjkwNmdObkJVRTNFa21ES1g1
            MHZnaWJjRkdMNll2NWlPZE5oYWhIaU0KLc3f13PFgY403BsAqY5TpDsioieShOAT
            zmdsr72RI1fiW01cxHBbxAcCTzRwQY9sw9X+YyGQ8eL47eWjb5G62Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUGRCc2dlakEzWHdEOXY3
            cmNaeThPd2hOMTJBOG9rY255dTdLTWNFbDNBCkVyL2I5QW42TG5ZYXVYK3FJbyto
            SmhsQzI4Q3R4Mld2ZCtSWjQ5TUlJVlEKLS0tIFJYL2J6bFpEdENjTFhTR09PUmIr
            dXJpSUloT2JBaFJCZG9jemFOdGpOVDgK4YaeAY/NzdlzZesle4+oQmYzHy43a/c2
            d1fOFKdnDDX+zwroXNPHpHo/8rg4pW9pvv70IIwoSYGeiT/TpM8TTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
    lastmodified: "2026-10-04T22:27:24Z"
    mac: ENC[AES256_GCM,data:ptHRKdBd8l5YX50US4n7oh9CWyWVlDY32M6ihhzkCu4/AyqufEJl3yCFR5zhpalT7xmVbWc7wZB5eR7J8aCAYTJ6+6Chn0qFQErpzihi0vb0oufEp+jd0+8mjNcfSLbISWGN2YWcQz08ytDcNsnNX5cxjMulEK2BgC+qxZBycAo=,iv:3TNSG83chVnQrSHcrcjKvHSCHjnBiZBif7/23s9zEyc=,tag:/MCP77oNH8XoVUePIU3gpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
