apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: monitoring
  labels:
    alertmanagerConfig: discord
spec:
  route:
    receiver: discord
    groupBy: ["namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    matchers:
      - name: alertname
        value: Watchdog
        matchType: "!="
  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: webhook-url
          sendResolved: true
