apiVersion: ENC[AES256_GCM,data:w6s=,iv:34CKTD40rxmg5v4E6UtgNhgZgqeMkCfUc6BfskPimS8=,tag:F15L+1RxgzejR6CBWVh4Ug==,type:str]
kind: ENC[AES256_GCM,data:s1lwylXp,iv:fQU9m3JNvQkpRYcxepJR+5CbrMKukmXNMQ1UuWtIq5I=,tag:l2/GfV6sEpAvmQsozNpNEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZHV1eIUX6yd4odyIfhqDrGU4/gk=,iv:J2Mw2KS5G4ZAfYBf1QttvFlh2JZ7zXypjIOQB6YOjdY=,tag:wpz70DQ+PeSWI4+4/MF2Yw==,type:str]
    namespace: ENC[AES256_GCM,data:m+JOkQ0dQY09mg==,iv:VYP7lFLRMPhdZqT3fOyXe2Op66wTXOO11igtS5kM5K4=,tag:vCIc/3EruMnNIv0mlm1SZA==,type:str]
type: ENC[AES256_GCM,data:uXWNaVbU,iv:TlEAihYxzqXQOW+WiMI51oNE9WC2+AY7V1enteOlb5E=,tag:nNnF7Zt01STVjyi7soxyzg==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:ZBihJFWN6nus,iv:VLnkOA8GOE15hmGqoGukPsnaK/R1k8Mbe4PbaWvwkII=,tag:k4ft5ZuadRbhVeKAUp/uqw==,type:str]
    admin-password: ENC[AES256_GCM,data:SodVMpBETM7aN0uhGYM=,iv:IIurN74wFELSXGvNHjmAeysrL+fb9d7X9kk9UO7tOj8=,tag:zGRewzt+y0f/Ogc1ZDAz3Q==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RnNhdFo4OUx2dzZqa1k3
            bHpGQUkrTGt2NXNUWlZLYUh5YWMyTC9HWFNrClpsNnBNY2lrMWxRNGIzUXB4NzVZ
            SUpuUTBXb2dmb3EzWTRBWmIwalgzTDQKLS0tIGpSTThOM1RoUitYTnk2bDNtU0Rz
            c3NPZHFmTDBOMlNlK1BqZVFvcTVBLzQKMq3tYR0edMmyx6bV5ymuOKjXGox8bV2H
            Yc2Shb6h/HUrJNfCpFpm0Ay0PSip49zdbHwKr+ESPOp5VhwvnNZUJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVVdWR2Q4enh5VXhMU3Ur
            M3U3amFVSkhhMXFLcklTUjgrN3NjdXI0UEVRClptS2dtdGZQVlJoY2duMDNnS2ZJ
            YVFkbm1pMEtrN3hSTlNBbnBRQnlWMFUKLS0tIE5sNWNwQWtDOEtmUzBQQkJYVWtN
            ajlmOUtwcU1lS2VqZnJYNmFMWEZhWVkKHZIssHEHnSibs9jyFpIOuZuL/FUU5fZ3
            2RiqWQ2fw6K2wCPpqXJS6y1yhuE1X0CRyUheGf+rTWQaUwLu1tmL8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU0FqYVplRFZZUjYzN1VD
            QTFYdkc3U2hXNDNQeHNCcnJpQUxyVUMvT1JjCmlUWkpqYjNLTi95Yzdqc2VkRXRJ
            U1dRNG1OdjJ5WE5GejUweGQ1ZWdBN2sKLS0tIHNuOGFTczg1V1RmdFlzY0doNExm
            cHlhdHV5b2dyK2FqRFlXalZTN3RqUzgKt4WyykZPomU72/e9xKJry6yMA65Y86cS
            ObakX533u2fSN7GFB+pPxUW3UFbpv1gTWtx7CuR0u7XzOQyjg1eehA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvamNYWld3b0VKR3RCaUJU
            QXpmTXNBdTZRMXE4K3hNSEdXR0lManpPclNFCm5wem5QblRrZ1U3SDh5RHFYVE14
            T0NrOFZ2RC9iNitIL3hxN3pqc2R2UkUKLS0tIGhvQm5ESkRsS0ZiYTFVRTJhNzZP
            Mmw4MHRsZ0RacmlLQitaZVRldCtqVmsKh5DIgh8lUKVK8ddW8uY0gjPRLajgHblP
            UYqZIDw1pY1Ub6GwhHIeDDqSpI33CPDyf8alqmz+PLfiCyzAFNG4Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T02:58:24Z"
    mac: ENC[AES256_GCM,data:eIWpHbMt0ZC/5pqYYs5L3bjkDNK4yyw/95gZqlMeVZOpw0RsY1BAf84aN/IuzEh0Jl/XKrSVldvcExIGAmf19fFablLTufwn3pYhdoRXXhS4QDVFJBHRnCIbwizrhZUnLcyAP7wGgBCgfCPF19/N2D1eoMgSTI0JBE7wq21bq3A=,iv:khpzJrQO0V3MNynmJMx0TvbyUrA616MJd/+7qN6/2X0=,tag:pf9OnGkATVbb06EkqcJlbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
