apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml 
  - source.yaml
  - pvc.yaml
  - secret-password.yaml
  - release.yaml
  - route.yaml
  - dns-service.yaml

patchesStrategicMerge:
  - deployment-persistence.yaml
