apiVersion: ENC[AES256_GCM,data:gh0=,iv:KH4+D33HOGGY5pS6B6oMacHNPt6etIHfAg1nwR2+xHs=,tag:ISZtZfTpPFfD41OavH9OhQ==,type:str]
kind: ENC[AES256_GCM,data:FzwRo7J5,iv:qyqx74dhYVMYmPrRBMFzq+fbJecoRNGg7nG4kU8eUrY=,tag:HmgRcKWWD+hpsqlHm3wVXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aNHOFVim2hblstJfdumq,iv:uN1ZLc3RoYH4SDRbwR/28CzywPjCjGPghL/q1s9JoUE=,tag:LA1rOmH80rCG8FI6ANXMcQ==,type:str]
    namespace: ENC[AES256_GCM,data:fY5RtBdD,iv:GCbWBo7Rf4lBhg3G6bl0DDjiL9HJaYEg5z2us7CKGnA=,tag:BIWFhylYHoqHSCJd0nYITQ==,type:str]
type: ENC[AES256_GCM,data:DXUXHT0I,iv:e/cFGahTDXgKw9ZRrKi6qDWJE2+kF0LHx2/EBV8j1/4=,tag:FKQfudBcvjDrsJpb/aKbPg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:hBts2QmNIsrjlvZPKCg=,iv:khkIT0s8JpWdcKBIVg3knzaxibEA9UJnEWUBUYq8i3Y=,tag:HD4meTX/7z6tcKwhfNmj6Q==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQkRxMEozSTFZUk5ESURN
            c2dDS2N0eVk3QmxJc0FxaTdiRDkza0VLS0VzCjEvRWduWUp4SnJ2UWFNMVkxSk5L
            emk1WVJYNUtsNnlkcTJESk03REk4ZXcKLS0tIHJOWlhQYVpacGcwK1daVDJIalFs
            TnNmeVJibXoyWXJmOGtodllmUFI4MW8Kd8XGTgZThcVkNvRro6YASUfen063dYNS
            NnPxPPv5xS5+KMW4UiYwgamRz5A7DvkvxPOT3ai99rbWdGEgFDLe5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWXRkQ2FBVUhnZ0RYd3Z3
            QWVEb2pwWUc1d05odTF0YXBRaHNjcDYwWVRFCnVKTjZrYjRoYmlXbXpUS2NwV1Zq
            UWpyay9lT1NPRjQxd1Uvc01keE9jWmcKLS0tIFVseUZ6OThXUUdyb2dmYmdaaHd5
            WHNLM3RENkRMQzhqMEJkdjE0Ujh4K3MK97XjO5/Mpe8IuqXO3iAEiw4LqWRjfJvf
            eSb6taVByR1ojuQvAYD7nzt5rXiwx9/L64Svem76if85tnwwv4H8Eg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd0pUTWFCNEJIK3kxK2hQ
            QjE2NDJWZmlsbVhnUzFXZy9PdmVTVGhRMnlvCkpnZGlpTEx4bnFWNWo2V01BMkRD
            aE9tSUZGWHJlY2tFMW43MzZVYklDVGMKLS0tIDFhWUdwaUgrTnVGNEt3ZWNyRUhB
            eWo2cGxrSUd1dElCRWt3U2dZbm1SME0Ko6guVx3g+BBjWJXlyJJus6pcecQcbLUN
            KQorG60k5iwI9CxtvXKbR7rFZEYjF0h86RYRcFF+W2sNjHPoPmP3uA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycFM3c0JjamUwakRsdENO
            WU13TTFaSGVreEZSdHdBejcrODVoRSs2Qmk4CkdlcTZUUWN3TkpTa1BwanhsNHpE
            TlU1NCtBRy9ESnpHeWtuQXhyVEtaRFEKLS0tIGo0Z2pvTjQwajk5OVhQQkh6VXA5
            Wnl6QUV4S3FuYllNZWdLVHlla1FMeDgKcfdVqcFxL01vjLerBKYX7zTzPsuWvvll
            Q9Svxwa6Fu8o+nPmgvHgU8WhsaR7D21VZUk5j4q6uVZ75VNM71agJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T23:24:39Z"
    mac: ENC[AES256_GCM,data:GBQfttd1Y8gM1Xo5qSvVqTqcoK+rTGMbIWPdi0xn9Nz9b4uJ/zzESBr2nhIvAOr8mMo3bYxz9S1Y36sPTrTDmGl1d3ZPC0xfP3sUNWHygN7MxqgJdM9d2VjRQh7m8vaC9N72H3MujjjK6CHqiiqBea734GnDWLqpo0YOtXu1dDw=,iv:spTtZR63X9nQbVvC83Ek41UJZem0FiKjBbvVbayRwNE=,tag:XWfrxW+205BWS+bNR6N8Tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
