apiVersion: ENC[AES256_GCM,data:CA4=,iv:ZIx5HAmGM1nWpe7oRoyuAZRRhbOcrwTvzSEY8/f+2yw=,tag:WYpU28eJ8tqkE4Gz2DsG+A==,type:str]
kind: ENC[AES256_GCM,data:5yrRMnU6,iv:zHsd/XVLcFIk1v85IxyPKE3B6ezr+ytDtMg4+KyPA98=,tag:qQzI6pYhget3bs2kyHswMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1HNndwnfvAKX3IV70w==,iv:vWX8Fl26z/t+4IK/FBuN5dZzXBDGdw+EGElGZxhhHsY=,tag:cAQfNsNlUfFL6hnw5AUqFA==,type:str]
    namespace: ENC[AES256_GCM,data:ZTRHrUfJ,iv:e8Jq62z+9jNVDaGPWftCwNA0cl6gAmAnvmAzmRjNAkA=,tag:YtlYcQQN/Gm4vLpqU+Nr6w==,type:str]
type: ENC[AES256_GCM,data:dArchmI+,iv:2CUdLUv/48DLBUF2OLfTyIZZyQVFVr162LmbKc1qwHg=,tag:JW8cr9aoQXZuDhspN530OQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:PXu4QOy7oA==,iv:KpW7AX0fzwx0JUuBxQfQqoWxKjZtC/PPe6XVHDPsYj0=,tag:mny9Gz/JOHEISfCYmPjs3Q==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWWhaZklQbzZLOGU2eEp1
            STZrNHlWK3o0YTJPNTdjdmxQZlA4TW9vcjJRClM2VWxzaFVJc3QxSlZzSU8vd3ZE
            bzFyb1RtaGxzOWJ1M010Z1I0VmgvbU0KLS0tIFRsblRwZmxLU3JtbkVta2FndVNU
            RHFEdW1FQXhodFM0em1UZnpTNU1PelkK1X8OUK4Wb5rF/yBvC/ZGgsT5q5hpXb/h
            /u9xbuuJiqb9ef5x9s7VIrl9UjcqMoOdIwG719epjCiORjgTLbyQiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQjhsRmhHYTlEaFpCdWMw
            WGkwK3BkeVBoTE9KU3FPU0RxZElGdnplclFFCmF6UmM5ejF0d0ozekRZWDJDSkh0
            NktyK0M2b2lCbGM5T3NLWWNFSXRjMG8KLS0tIGxWd2NYcHJmeWt1RzBPb0g4ejZX
            cjliTitSRGVIZDVmNVZFNTZpVXhqdk0KQTWfuLdXbWojzOkak76pIxN2cKU3McD4
            //s79Rgmhkw0MiBLDGTBUbWjkuXeFAPOE3dQ6PbdTZgti5QsevG65g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdVlrc3BxVStia0RFdFEy
            amVyYTR4UGJMV0lFNWJQWUhncG16UTFza3djClFNa0UzL2M2QXJtOXY1ZXBBSkdh
            aDVyN1dZemMybTc3N2d2dTNCaVY2SWsKLS0tIGFvNHJCNU9OWTRldGNoNHFzSVNV
            VU53NVNIMEhGc3pjMEwvL04xdEF2dU0Kih55pfSSrLYWVL6ncTBoZENQzdt7sI6i
            5oM413B1GaxeNZIF3Ku6LwraTHaBc4cNULdCMLWQnU16/USHjMFg4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOTZobVI2SHZrUkt4aHVa
            UGlqd1AxU1NES1RiVmZtS1o4UlE4VlRvTkZFClorUFNoOHJnR3haV1ZEWEtTMVdh
            d3E4cW1xUVRQK3NGVUNQaitLVHhZZEkKLS0tIHpWYTZBZkhnZFh2a2FFamw5cFZS
            akRqWFJPSUNuMWdieVF2eXM3TFhXMEUKa+8a3pzTt5aaKkfWwOn65i0HcHP7e7Bz
            nJTaSMmZsLhsQi9bJfqkJ84yTyE4ISDBRhJZJ5U+jW2emyzOSkVk/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:49:25Z"
    mac: ENC[AES256_GCM,data:tSncak0CGSr2w5fjGcVDelhCj9kr4MXgR4CHwrNjspgFV2q7RRwRosOvk3+b6Zfq71tsM+3y5VPjh5Ud7yV7OkKkNY0aPdB8kGP7chmHswRENCsUEjG4U5spv25ufHh0HkN5ed6rPaGCJSCU/oWkzRIWAZCPkmVd3Khtd0eSo/E=,iv:bjW6X8NXe7kWk0b9Nphh7evINxQtHVSmsV8sGc3TXsI=,tag:arbWcnLRHk1VmWkB4PVzLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
