apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultwarden.yaml
  - vaultwarden-secret.enc.yaml
  - discord-bot.yaml
  - discord-bot-secret.enc.yaml
  - minecraft.yaml
  - minecraft-rcon-secret.enc.yaml
